name: Check Typing

on:
  # Run this workflow on pushes, pull requests to main, or when manually triggered.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_typing:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the latest code version
      - name: Check Out Repository
        uses: actions/checkout@v3

      # Step 2: Set up the required Python version
      - name: Configure Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the target Python version

      # Step 3: Install Mypy Static Type Checker
      - name: Install Mypy
        run: |
          python -m pip install --upgrade pip
          pip install mypy

      # Step 4: Check typing annotations using mypy
      - name: Run Mypy for static type check
        run: |
          mypy borb/
