name: Check Argument Name

on:
  # Trigger the workflow on push and pull request events
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  check_imports_dependencies:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Choose your Python version

      # Step 3: Check whether the argument names are meaningful
      - name: Check whether the argument names are meaningful
        run: |
          python ./.github/workflows/check_argument_name.py borb/
