name: Check Code Formatting with Black

on:
  # Run this workflow on pushes and pull requests to the main branch, or when manually triggered.
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_code_formatting_with_black:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Retrieve the latest code version
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up the required Python version
      - name: Configure Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the target Python version

      # Step 3: Install Black code formatter
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      # Step 4: Check code formatting with Black
      - name: Run Black for Code Formatting Check
        run: |
          black --check borb/
